# 블로그 기본 정보
title: "GiuNash Station" # 블로그 제목
subtitle: "My Personal Space" # 부제목
description: "Welcome to my personal blog using the WuK theme." # 설명
url: "https://gyutrange.github.io" # GitHub Pages URL
baseurl: "" # 루트 URL (루트에 위치하므로 비워둡니다)
lang: "en" # 언어 설정
timezone: "Asia/Seoul" # 시간대

# 소셜 링크 설정
social:
  - name: GitHub
    link: https://github.com/gyutrange
  - name: LinkedIn
    link: https://linkedin.com/in/gyutrange

# 테마 및 사용자 정의 설정
remote_theme: "wu-kan/jekyll-theme-WuK" # WuK 테마 적용
plugins:
  - jekyll-seo-tag # SEO 최적화
  - jekyll-feed # RSS 피드 생성
  - jekyll-sitemap # 사이트맵 생성
  - jekyll-redirect-from # 리다이렉션 설정

jekyll-theme-WuK:
  default:
    body:
      theme-base: theme-base-07 # 테마 색상 (07~0f 변경 가능)
      layout-reverse: false # Sidebar 위치 (false: 왼쪽, true: 오른쪽)
    sidebar:
      disable: false # Sidebar 활성화 여부
      avatar: # Sidebar에 표시할 아바타 설정
        enable: true
        img: "/assets/images/avatar.png" # 아바타 이미지 경로
      nav: # Sidebar 메뉴
        - title: '<i class="fa-solid fa-home fa-fw"></i> Home'
          href: /
        - title: '<i class="fa-solid fa-comment fa-fw"></i> Comments'
          href: /comments/
        - title: '<i class="fa-solid fa-archive fa-fw"></i> Archive'
          href: /archive/
        - title: '<i class="fa-solid fa-tags fa-fw"></i> Tags'
          href: /tags/
    page:
      title:
        enable: true
      wordcount:
        enable: true
        prepend: '<i class="fa-solid fa-file-word fa-fw"></i>'
      readtime:
        enable: true
        prepend: '<i class="fa-solid fa-clock fa-fw"></i>'
        unit: mins
        divided_by: 300 # 평균 읽기 속도: 1분당 300자

# 댓글 설정
comments:
  append: |
    <script
      repo="gyutrange/comments"
      src="https://utteranc.es/client.js"
      issue-term="pathname"
      theme="github-light"
      crossorigin="anonymous"
      async
    ></script>

# Google Analytics (선택사항)
google_analytics: ""

# SEO 설정
jekyll-seo-tag:
  twitter:
    username: "your_twitter_handle"

# Markdown 및 하이라이터 설정
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      disable: false
      line_numbers: false
    span:
      disable: false

# 페이지 레이아웃 기본값 설정
defaults:
  - scope:
      path: ""
    values:
      layout: "post"

# 플러그인 설정
permalink: pretty
future: true
