#
# 이 문서는 블로그 설정 정보를 포함합니다. 본인의 블로그를 개인화하려면 편집하세요.
#

# 블로그 이름. "LOFFER"를 원하는 블로그 이름으로 변경하세요.
# 주의: "name: LOFFER"에서 콜론(:) 뒤에 공백을 반드시 포함해야 합니다.
# 해시(#) 뒤에 있는 내용은 주석이며 프로그램에서 무시됩니다.

# 블로그 이름/설명
name: GiuNash Station
description: Dev & Sec

# 블로그 URL 입력 (GitHub Pages에서 제공하는 기본 URL을 사용하는 경우 생략 가능)
url:

# 블로그 저장소의 이름 (예: http://yourusername.github.io/repository-name)
# 저장소 이름을 "/repository-name" 형식으로 작성
baseurl: /

#
# 아래의 설정은 선택 사항입니다.
#

# 블로그 로고 이미지 URL. 300px × 300px 이하 크기를 권장합니다.
avatar: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/logo.png

# 브라우저 탭에 표시되는 favicon 이미지 URL. 64px × 64px 이하 크기를 권장합니다.
favicon: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/favicon.png

# 메뉴 항목 설정
navigation:
  - name: Home
    url: /
  - name: About Me
    url: /about
  - name: Archive
    url: /archive
  - name: Category
    url: /tags

# 한 페이지에 표시할 게시물 수
paginate: 8

# 게시물 요약을 구분하는 마커
excerpt_separator: <!-- more -->

# 블로그의 소셜 미디어 링크. 페이지 하단에 아이콘으로 표시됩니다. 원하는 항목만 입력하세요.
footer-links:
  weibo:
  behance:
  dribbble:
  email:
  facebook:
  flickr:
  github: gyutrange
  instagram:
  linkedin:
  pinterest:
  rss:
  stackoverflow:
  tumblr:
  twitter:
  youtube:

# 블로그 하단에 표시되는 텍스트
footer-text: Copyright (c) 2024 Giunash Station

#
# 댓글 설정 (다양한 댓글 시스템 중 하나만 활성화하세요).
#

# Disqus 댓글 설정. shortname을 입력하세요. Disqus 웹사이트에서 shortname을 설정해야 합니다.
disqus: loffer # shortname

# Gitalk 댓글 설정. 관련 정보를 입력하세요.
gitalk:
  clientID:
  clientSecret:
  repo:
  owner:
  proxy:

# Google Analytics 추적 코드
google_analytics:

# Utteranc 댓글 설정. 관련 정보를 입력하세요.
utteranc:
  repo: # GitHub 저장소 경로. Utteranc 공식 문서를 참고하세요: https://utteranc.es

#
# 아래 설정은 수정하지 않아도 됩니다.
#

permalink: /:title/
paginate_path: /page:num/

# LOFFER 릴리스 버전
version: v1.2.0

# Jekyll은 이제 Kramdown 마크다운만 지원합니다.
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Sass partial 디렉토리를 설정합니다.
sass:
  style: :expanded # 압축된 스타일을 원한다면 :compressed로 변경하세요.

# 사용 플러그인
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# 프로덕션에서 제외할 파일
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
