# 블로그 기본 정보
title: "Gyutrange's Blog" # 블로그 제목
description: "Hack'em all ^~^" # 블로그 설명
baseurl: "" # 루트 URL (서브디렉토리가 없으므로 빈 값으로 둡니다)
url: "https://gyutrange.github.io" # GitHub Pages URL
lang: "en" # 블로그 언어 (기본값 'zh'를 영어로 변경)
timezone: "Asia/Seoul" # 시간대 설정

# Sidebar 및 테마 설정
defaults:
  - scope:
      path: "" # 프로젝트의 모든 파일에 적용
    values:
      jekyll-theme-WuK:
        comments:
          append: |
            <script
              repo="gyutrange/comments" # 본인의 GitHub 댓글 저장소로 변경
              src="https://utteranc.es/client.js"
              issue-term="url"
              theme="github-light"
              crossorigin="anonymous"
              async="async"
            ></script>
        default:
          body:
            theme-base: theme-base-07 # 테마 색상
            layout-reverse: false # Sidebar 위치 (false: 왼쪽, true: 오른쪽)
            sidebar-overlay: true # Sidebar 고정 여부
          html_lang: en # 언어 코드 (영어로 변경)
          sidebar:
            disable: false # Sidebar 활성화
            avatar: # 아바타 설정
              enable: true
              img: "/assets/images/avatar.png" # 아바타 이미지 경로 (사용자 정의)
            nav: # 네비게이션 메뉴 설정
              - title: '<i class="fa-solid fa-home fa-fw"></i> Home'
                href: /
              - title: '<i class="fa-solid fa-comment fa-fw"></i> Comments'
                href: /comments/
              - title: '<i class="fa-solid fa-archive fa-fw"></i> Archive'
                href: /archive/
              - title: '<i class="fa-solid fa-tags fa-fw"></i> Tags'
                href: /tags/
              - title: '<i class="fa-solid fa-user fa-fw"></i> About'
                href: /about/
            simple_jekyll_search: # Sidebar 검색 설정
              enable: true
              full_text_search: false # 전체 텍스트 검색 (성능 이슈로 비활성화)
              append: |
                <style>
                  #sidebar-search-input {
                    background: none;
                    border: none;
                    color: White;
                    width: 100%;
                  }
                  #sidebar-search-results-container {
                    overflow: hidden hidden;
                    max-height: 66.6vh;
                  }
                  #sidebar-search-results-container:hover {
                    overflow: auto auto;
                  }
                </style>
                <input
                  id="sidebar-search-input"
                  placeholder="Search Blog"
                />
                <ol
                  id="sidebar-search-results-container"
                ></ol>
                <script
                  src='https://cdn.jsdelivr.net/npm/simple-jekyll-search@1.9.1'
                  async='async'
                  onload='
                    SimpleJekyllSearch({
                      json: "/assets/simple-jekyll-search/search.json",
                      searchInput: document.getElementById("sidebar-search-input"),
                      resultsContainer: document.getElementById("sidebar-search-results-container"),
                      searchResultTemplate: "<li><a href={url}>{title}</a></li>",
                      limit: 99,
                      fuzzy: true
                    })'
                ></script>
            jekyll-toc: # Sidebar 목차 설정
              enable: true
              prepend: | # 목차가 길 경우 자동 스크롤
                <style>
                  #toc {
                    overflow: hidden hidden;
                    max-height: 66.6vh;
                  }
                  #toc:hover{
                    overflow: auto auto;
                  }
                </style>

# Google Analytics (선택사항)
google_analytics: ""

# SEO 설정
jekyll-seo-tag:
  twitter:
    username: "your_twitter_handle"

# Markdown 및 하이라이터 설정
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      disable: false
      line_numbers: false
    span:
      disable: false

# 페이지 레이아웃 기본값 설정
defaults:
  - scope:
      path: ""
    values:
      layout: "post"

# 플러그인 설정
permalink: pretty
future: true
